var Deck = require("./component_deck.js");
var Index = 0||1||2||3||4||5||6||7||8||9||10||11||12||13||14||15||16||17||18||19||20||21||22||23||24||25||26||27||28||29||30||31||32||33||34||35||36||37||38||39||40||41||42||43||44||45||46||47;
var Card = Deck[Index];
var P1L1 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var P1L2 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var P1L3 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var P1L4 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var P2L1 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var P2L2 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var P2L3 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var P2L4 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var BL1 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var BL2 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var BL3 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
var BL4 = [undefined, undefined, undefined, undefined, undefined, undefined, undefined];
console.log(Deck[0].IsPlayerOne);